
[General]
	#What Color should the overlay at the second corner be [Format: #RRGGBB]
	#Range: > 0
	second_corner_overlay_color = 6488064
	#BurnTick consumption of the quarry in idle mode per second
	#Range: 0 ~ 1000
	quarry_idle_consumption = 1
	#What Color should the overlay at the first corner be [Format: #RRGGBB]
	#Range: > 0
	first_corner_overlay_color = 1139456
	#Silk Touch mode BurnTick consumption
	#Range: 0 ~ 1000
	quarry_mode_silktouch_consumption = 200
	#Speed 1 BurnTick consumption multiplier
	#Range: 0.0 ~ 5.0
	quarry_speed_one_multiplier = 1.0
	#Speed 3 BurnTick consumption multiplier
	#Range: 0.0 ~ 5.0
	quarry_speed_three_multiplier = 1.5
	#Speed 2 BurnTick consumption multiplier
	#Range: 0.0 ~ 5.0
	quarry_speed_two_multiplier = 1.25
	#Efficient mode BurnTick consumption
	#Range: 0 ~ 1000
	quarry_mode_efficient_consumption = 80
	#Void mode BurnTick consumption
	#Range: 0 ~ 1000
	quarry_mode_void_consumption = 100
	#Default mode BurnTick consumption
	#Range: 0 ~ 1000
	quarry_mode_default_consumption = 100
	#Fortune mode BurnTick consumption
	#Range: 0 ~ 1000
	quarry_mode_fortune_consumption = 200
	#Speed 4 BurnTick consumption multiplier
	#Range: 0.0 ~ 5.0
	quarry_speed_four_multiplier = 1.75

